### ISSUE TITLE
Error while compiling: "-Werror=implicit-function-declaration"

### ISSUE THREAD

**Issue by gabrielgagz** [fgl27/qcacld-2.0#1]
Every time i try to compile the module, i get this error:

` drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_main.o
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_main.c: In function '__hdd_netdev_notifier_call':
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_main.c:755:9: error: implicit declaration of function 'sme_ChAvoidUpdateReq' [-Werror=implicit-function-declaration]
         sme_ChAvoidUpdateReq(pHddCtx->hHal);
         ^
cc1: some warnings being treated as errors
scripts/Makefile.build:308: fallo en las instrucciones para el objetivo 'drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_main.o'
make[3]: *** [drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_main.o] Error 1
scripts/Makefile.build:455: fallo en las instrucciones para el objetivo 'drivers/staging/qcacld-2.0'
make[2]: *** [drivers/staging/qcacld-2.0] Error 2`

`4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.2.0-3ubuntu11~16.04' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.2.0 20160901 (Ubuntu 6.2.0-3ubuntu11~16.04)`

I'm trying to compile the module for the Razer Forge kernel sources:  http://developer.razerzone.com/forge-tv/developer-setup/

**Comment by fgl27** [comment]
You are compiling this driver, from 8084-wifi branch?
have you try the other branch?

I don't have any of those error, I use Ubertc tool chain to compile both branch
https://bitbucket.org/UBERTC/arm-eabi-4.8

Or stock google arm-eabi-4.8 to compile cm-13.0
https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8

the dif between the branch is very little 
https://github.com/bhb27/qcacld-2.0/commit/9144d2fb6c302c8faae69dd62fad0312fa691611

there is others toolchains that can compile that but may need adaptations... What is the kernel source?
Or you are just building the module?

And check the defconfig quark_defconfig
#
# Qualcomm Atheros CLD WLAN module
#
CONFIG_QCA_CLD_WLAN=m
CONFIG_QCACLD_WLAN_LFR3=y
CONFIG_PRIMA_WLAN_OKC=y
CONFIG_PRIMA_WLAN_11AC_HIGH_TP=y
CONFIG_WLAN_FEATURE_11W=y
CONFIG_WLAN_FEATURE_LPSS=y
CONFIG_QCOM_VOWIFI_11R=y
CONFIG_WLAN_FEATURE_NAN=y
CONFIG_QCOM_TDLS=y
CONFIG_QCOM_LTE_COEX=y
CONFIG_WLAN_FEATURE_MEMDUMP=y
CONFIG_WLAN_OFFLOAD_PACKETS=y

**Comment by gabrielgagz** [comment]
Thanks alot, the config did the trick. But probably is something broken, if you not enable all the settings the cmpilation fails...Also, the size of the module is like 70mb (works perfect)...is this ok? Thanks again

**Comment by fgl27** [comment]
Some particularly defconfig make a particularly file to compile then if you don't use them all you end up having a missing function that is on a not compiled file...

The size is wrong but after the compilation that happens, to make it "slim" you use this
${CROSS_COMPILE}strip --strip-unneeded ./path_to_the_modules_folder/*
were ${CROSS_COMPILE} is the toolchain like this
export CROSS_COMPILE=$HOME/android/n/prebuilts/gcc/linux-x86/arm/arm-eabi-4.8/bin/arm-eabi-
or
export CROSS_COMPILE=$HOME/android/temp/arm-eabi-4.9/bin/arm-eabi-
my final size is under 5mb

the script I use to build and the kernel source
https://github.com/bhb27/BHB27Kernel/blob/Custom_Nougat/build/how_to_build_this.sh
I miss to give you that before...
:+1:
